### ISSUE TITLE
[MOBILE] - Ne jouer l'aide au démarage qu'une seule fois

### ISSUE THREAD

**Issue by Asiberus** [MesseBasseProduction/BeerCrackerz#16]
Sur mobile ne jouer le tuto d'aide au démarrage qu'une seule fois.
Proposer dans les param ou dans la page de profile un bouton pour rejouer le tuto.
Le switch n'est pas assez visible actuellement, je pense que beaucoup de gens vont passer à coté.

**Comment by ArthurBeaulieu** [comment]
Not relevant on web repo, issue create on https://github.com/MesseBasseProduction/BeerCrackerzMobile/issues/11
