### ISSUE TITLE
Gestion des caractères spéciaux

### ISSUE THREAD

**Issue by Silver958** [MesseBasseProduction/BeerCrackerz#21]
Les caractères spéciaux ne sont pas très bien gérés dans les descriptions de spots

**Comment by ArthurBeaulieu** [comment]
@Asiberus je pense que ça concerne seulement le mobile, je regarde ça

**Comment by ArthurBeaulieu** [comment]
Après analyse, c'est un souci de session sur Flutter car c'est proprement sauvegardé en bdd. Ça devrait être un quick win

**Comment by ArthurBeaulieu** [comment]
Résolu !
https://github.com/MesseBasseProduction/BeerCrackerzMobile/commit/c5eb99ceb5e6566d3be8757b9413353915120dc4
C'était un décodage utf8 qui manquait sur les responses serveurs au addMark.
